package stack

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"slices"

	"github.com/letya999/hermes-hub/internal/media"
)

// Generated by the isolated pinned-image capability probe. An upstream update
// must pass the probe and review its inventory diff before this list changes.
//
//go:embed hermes_capability_inventory.json
var managedInventoryJSON []byte

type HermesCapabilityInventory struct {
	Schema           int      `json:"schema"`
	SourcePin        string   `json:"source_pin"`
	InventorySHA256  string   `json:"inventory_sha256"`
	Platforms        []string `json:"platforms"`
	DisabledToolsets []string `json:"disabled_toolsets"`
}

func ManagedCapabilityInventory() (HermesCapabilityInventory, error) {
	var inventory HermesCapabilityInventory
	if err := json.Unmarshal(managedInventoryJSON, &inventory); err != nil {
		return inventory, err
	}
	if inventory.Schema != 1 || len(inventory.SourcePin) != 40 || len(inventory.InventorySHA256) != 64 ||
		len(inventory.Platforms) == 0 || len(inventory.DisabledToolsets) == 0 ||
		!slices.Contains(inventory.Platforms, "api_server") || !slices.Contains(inventory.DisabledToolsets, "terminal") || !slices.Contains(inventory.DisabledToolsets, "file") {
		return inventory, fmt.Errorf("invalid managed Hermes inventory")
	}
	return inventory, nil
}

// nativeCarveoutToolsets is the reviewed set of upstream toolsets an operator
// may re-enable for one runtime through `tools:` entries with `via: native`.
// Everything else in the inventory stays denied: platform adapters only open
// gateway listeners inside the agent, delegation/bot_room/a2a/coding spawn
// sub-agents whose literal toolsets bypass the denylist entirely, and
// hermes-*/context_engine surfaces reopen API paths the boundary removed.
var nativeCarveoutToolsets = map[string]bool{
	"file": true, "terminal": true, "memory": true, "skills": true,
	"todo": true, "web": true, "search": true, "browser": true,
	"image_gen": true, "video": true, "video_gen": true, "vision": true,
	"kanban": true, "session_search": true, "cronjob": true,
	"spotify": true, "homeassistant": true, "tts": true, "x_search": true,
	"feishu_doc": true, "feishu_drive": true, "clarify": true,
	"debugging": true, "project": true, "safe": true, "code_execution": true,
}

var nativeToolsetName = regexp.MustCompile(`^[a-z][a-z0-9_-]{0,63}$`)

// NativeCarveoutToolsets returns the sorted set of upstream toolsets a managed
// runtime may re-enable per space.
func NativeCarveoutToolsets() []string {
	names := make([]string, 0, len(nativeCarveoutToolsets))
	for name := range nativeCarveoutToolsets {
		names = append(names, name)
	}
	slices.Sort(names)
	return names
}

// ValidateNativeToolsets checks an operator-supplied carve-out list: exact
// reviewed names, deduplicated.
func ValidateNativeToolsets(names []string) error {
	seen := map[string]bool{}
	for _, name := range names {
		if !nativeToolsetName.MatchString(name) {
			return fmt.Errorf("invalid native toolset name %q", name)
		}
		if !nativeCarveoutToolsets[name] {
			return fmt.Errorf("native toolset %q is not carve-out approved", name)
		}
		if seen[name] {
			return fmt.Errorf("duplicate native toolset %q", name)
		}
		seen[name] = true
	}
	return nil
}

// disabledToolsets subtracts the operator's native carve-outs from the
// inventory denylist. Validate() runs ValidateNativeToolsets first, so any
// name reaching here is known and approved.
func disabledToolsets(s Settings) []string {
	inventory, err := ManagedCapabilityInventory()
	if err != nil {
		panic(err) // Corrupt compiled inventory must never render a permissive config.
	}
	carveouts := s.nativeCarveouts()
	disabled := make([]string, 0, len(inventory.DisabledToolsets))
	for _, name := range inventory.DisabledToolsets {
		if !slices.Contains(carveouts, name) {
			disabled = append(disabled, name)
		}
	}
	// Tool governance is a second, independent fence: a carve-out whose
	// native:<name> section is denied goes back onto the emitted denylist.
	for _, name := range carveouts {
		if !s.govAllows("native:"+name) && !slices.Contains(disabled, name) {
			disabled = append(disabled, name)
		}
	}
	slices.Sort(disabled)
	return disabled
}

func managedHermesConfig(s Settings) M {
	inventory, err := ManagedCapabilityInventory()
	if err != nil {
		panic(err) // Corrupt compiled inventory must never render a permissive config.
	}
	platforms := M{}
	for _, platform := range inventory.Platforms {
		platforms[platform] = []string{}
	}
	out := M{
		"model":             M{"default": s.Model, "provider": "custom", "base_url": s.ModelURL, "api_key": "${OPENAI_API_KEY}"},
		"platform_toolsets": platforms,
		"agent":             M{"disabled_toolsets": disabledToolsets(s)},
		// Only via: mcp-raw selections (organization-provided servers) render
		// here; every connector still goes through the ToolHub projection.
		"mcp_servers": rawMCPServers(s),
		"plugins":     M{"enabled": []string{}},
		"skills":      M{},
		"hooks":       M{},
		// A carved-out `memory` toolset still needs its subsystem flag; without
		// it the tool loads against a disabled backend and silently no-ops.
		"memory": M{"memory_enabled": slices.Contains(s.nativeCarveouts(), "memory"), "user_profile_enabled": false},
		// Voice lives on the gateway side: communication-hub transcribes and
		// synthesizes through the hub-stt/hub-tts sidecars. The in-runtime
		// upstream STT toolset stays sealed — the managed runtime never sees
		// raw audio and the denylist keeps it that way.
		"stt":      M{"enabled": false},
		"security": M{"allow_lazy_installs": false},
		// Literal-toolset sub-agents ignore the denylist (AIAgent receives no
		// disabled_toolsets on those paths): detached compression hygiene gets
		// ["memory"] and curator consolidation gets ["skills"]. The hygiene
		// agent is reachable only from gateway platform message handling
		// (gateway/run_turn.py) — managed runtimes expose just the api_server
		// platform and all ingress is the hub gateway, so the in-loop
		// ContextCompressor (a plain auxiliary call, no tools) is the only
		// compression path and is safe to enable. The curator stays sealed:
		// its detached agent would bypass the denylist with a live toolset.
		// threshold_tokens is the absolute cap so a 1M-window model compacts
		// predictably instead of quadratic-cost growth toward half the window;
		// micro_compact stays off to keep the prompt-cache prefix stable.
		"compression": M{"enabled": true, "in_place": true, "micro_compact": false, "threshold_tokens": 200000},
		"curator":     M{"enabled": false},
		"display":     M{"busy_input_mode": "queue", "long_running_notifications": true},
		"timezone":    s.Timezone,
	}
	// Carved-out web toolsets keep the operator's provider selection; the
	// managed egress relay decides which of their endpoints can actually be
	// reached.
	for _, name := range []string{"web", "search", "x_search"} {
		if entry := s.Tools[name]; entry.Via == ToolViaNative {
			if web := s.Web.config(); len(web) > 0 {
				out["web"] = web
			}
			break
		}
	}
	// The image_gen block is the runtime grant media.Session checks before
	// serving the ToolHub image tools: the capability profile admits the call
	// and this block wires the reviewed provider/model. Enabled under any
	// backend — the unmanaged render gates on the same Has() condition. An
	// operator that disables the feature revokes generation on the next
	// materialization without touching the profile.
	if s.Has("image_gen") {
		gen, err := s.ImageGen.Normalize()
		if err != nil {
			panic(fmt.Errorf("image_gen: %w", err)) // Validate() rejects it before render
		}
		out["image_gen"] = M{"provider": gen.Provider, "model": gen.Model, "delivery": gen.Delivery}
	}
	return out
}

// managedImageGenGrant is the normalized grant the managed contract carries:
// non-empty iff the image_gen tool entry is enabled. Render sites pass it as
// MaterializeOptions.ImageGen / HUB_MANAGED_IMAGE_GEN so the in-container
// preflight reconstructs the identical config block without consulting state
// the agent could edit.
func (s Settings) managedImageGenGrant() media.ImageGen {
	if !s.Has("image_gen") {
		return media.ImageGen{}
	}
	gen, err := s.ImageGen.Normalize()
	if err != nil {
		return media.ImageGen{} // Validate() rejects the settings before render
	}
	return gen
}

// ManagedImageGenGrant exposes the normalized grant to the supervisor, which
// reproduces this render's MaterializeOptions when it materializes the
// effective config for a spawned managed runtime.
func (s Settings) ManagedImageGenGrant() media.ImageGen { return s.managedImageGenGrant() }

// managedWebSettings returns the operator web selection only when a web
// family toolset is carved out natively — the same condition under which
// managedHermesConfig renders the `web:` block.
func (s Settings) managedWebSettings() WebSettings {
	for _, name := range []string{"web", "search", "x_search"} {
		if entry := s.Tools[name]; entry.Via == ToolViaNative {
			return s.Web
		}
	}
	return WebSettings{}
}
