package stack

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"slices"
)

// Generated by the isolated pinned-image capability probe. An upstream update
// must pass the probe and review its inventory diff before this list changes.
//
//go:embed hermes_capability_inventory.json
var managedInventoryJSON []byte

type HermesCapabilityInventory struct {
	Schema           int      `json:"schema"`
	SourcePin        string   `json:"source_pin"`
	InventorySHA256  string   `json:"inventory_sha256"`
	Platforms        []string `json:"platforms"`
	DisabledToolsets []string `json:"disabled_toolsets"`
}

func ManagedCapabilityInventory() (HermesCapabilityInventory, error) {
	var inventory HermesCapabilityInventory
	if err := json.Unmarshal(managedInventoryJSON, &inventory); err != nil {
		return inventory, err
	}
	if inventory.Schema != 1 || len(inventory.SourcePin) != 40 || len(inventory.InventorySHA256) != 64 ||
		len(inventory.Platforms) == 0 || len(inventory.DisabledToolsets) == 0 ||
		!slices.Contains(inventory.Platforms, "api_server") || !slices.Contains(inventory.DisabledToolsets, "terminal") || !slices.Contains(inventory.DisabledToolsets, "file") {
		return inventory, fmt.Errorf("invalid managed Hermes inventory")
	}
	return inventory, nil
}

func managedHermesConfig(s Settings) M {
	inventory, err := ManagedCapabilityInventory()
	if err != nil {
		panic(err) // Corrupt compiled inventory must never render a permissive config.
	}
	platforms := M{}
	for _, platform := range inventory.Platforms {
		platforms[platform] = []string{}
	}
	return M{
		"model":             M{"default": s.Model, "provider": "custom", "base_url": s.ModelURL, "api_key": "${OPENAI_API_KEY}"},
		"platform_toolsets": platforms,
		"agent":             M{"disabled_toolsets": slices.Clone(inventory.DisabledToolsets)},
		"mcp_servers":       M{},
		"plugins":           M{"enabled": []string{}},
		"skills":            M{},
		"hooks":             M{},
		"memory":            M{"memory_enabled": false, "user_profile_enabled": false},
		"stt":               M{"enabled": false},
		"security":          M{"allow_lazy_installs": false},
		// Literal-toolset sub-agents ignore the denylist (AIAgent receives no
		// disabled_toolsets on these paths): detached compression hygiene gets
		// ["memory"] and curator consolidation gets ["skills"]. Both are config
		// gated, so the managed profile switches the paths off entirely rather
		// than trusting a denylist that never reaches them.
		"compression": M{"enabled": false},
		"curator":     M{"enabled": false},
		"display":     M{"busy_input_mode": "queue", "long_running_notifications": true},
		"timezone":    s.Timezone,
	}
}
